### ISSUE TITLE
Pre-audit checklist

### ISSUE THREAD

**Issue by dcposch** [daimo-eth/p256-verifier#1]
- [x] Remove all commented-out code from P256Verifier.
- [x] Clean up code, add thorough inline documentation.
- [x] Remove reverts. EIP-7212 spec always returns 1 or 0, never reverts.
- [x] Combine test vectors in a clean JSON file. Use in `forge test`.
   - Wycheproof vectors
   - Sage vectors
   - others?
 - [x] Measure branch coverage
 - [x] Measure gas cost
 - [x] Deploy on Base Goerli
 - [x] Test in Daimo via 4337 contract account

**Comment by dcposch** [comment]
- [ ] Potentially formal verification. Will talk to Veridise

**Comment by nalinbhardwaj** [comment]
Audit is complete #23
